version: "3.8"

services:
  petclinic:
    build:
      context: .
      target: development
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_FLYWAY_ENABLED=true
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
