version: '3.4'

services:

  lab2:
    image: lab2
    ports:
      - 80:80

    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - type: volume
        source: lab2volume
        target: /data
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: letsencrypt
    restart: always
    command: certonly --webroot -w /var/www/certbot -d www.examplecom -d examplecom --non-interactive --agree-tos -m jalal0601@gmail.com
    depends_on:
      - lab2
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./certbot/www:/var/www/certbot/:ro
volumes:
  lab2volume:

networks:
  letsencrypt:

