version: '3.4'

services:
  lab2:
    image: lab2
    ports:
      - 80:80
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: volume
        source: lab2vol
        target: /data

volumes:
  lab2vol:
